#ifndef __ro_hp_calculator_main_frame__
#define __ro_hp_calculator_main_frame__

/**
@file
Subclass of RoHpCalculatorMainFrameBase, which is generated by wxFormBuilder.
*/

#include "wxFormBuilder/ro_hp_calculator_main_frame_base.h"

//// end generated include

#include "../ro_hp_calculator.h"

namespace rco {

/** Implementing RoHpCalculatorMainFrameBase */
class RoHpCalculatorMainFrame : public RoHpCalculatorMainFrameBase
{
protected:
    // Handlers for RoHpCalculatorMainFrameBase events.
    void CharacterChoiceOnChoice(wxCommandEvent& event);
    void RoHpPaintPanelOnLeftDClick(wxMouseEvent& event);
    void RoHpPaintPanelOnMouseWheel(wxMouseEvent& event);
    void RoHpPaintPanelOnPaint(wxPaintEvent& event);
    void VitChoiceOnChoice(wxCommandEvent& event);
    void MhpPercentageChoiceOnChoice(wxCommandEvent& event);
    void ExtraHpTextCtrlOnText(wxCommandEvent& event);
    void ExtraHpTextCtrlOnTextEnter(wxCommandEvent& event);
    void ExtraHpTextCtrlOnTextMaxLen(wxCommandEvent& event);
    void ExitMenuItemOnMenuSelection(wxCommandEvent& event);
    void AboutMenuItemOnMenuSelection(wxCommandEvent& event);
public:
    /** Constructor */
    RoHpCalculatorMainFrame(wxWindow* parent);
    //// end generated class members
private:
    void PrepareCharacterJobChoice();
    void PrepareVitChoice();
    void PreareMhpPercentageChoice();
    void SetExtraHpTextCtrl(wxString& input_value);

    void CalculateAndSetMaxHp();

    RoHpCalculator ro_hp_calculator_;
};

}; // end of namespace "rco"

#endif // __ro_hp_calculator_main_frame__
